package constants

const(
NOME_CEDENTE_COL = 4
DOC_CEDENTE_COL = 5
NOME_SACADO_COL = 6
DOC_SACADO_COL = 7
VALOR_NOMINAL_COL = 9
VALOR_PRESENTE_COL = 10
VALOR_AQUISICAO_COL = 11
NU_DOCUMENTO_COL = 16
)